#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "common.h"
#define BUF 500

// analysis.h???
typedef struct hcct_node_s hcct_node_t;
struct hcct_node_s {
    UINT32          routine_id;
    UINT16          call_site;
    UINT32          counter;
    //char*         info_routine;    
    
    hcct_node_t*    first_child;
    hcct_node_t*    next_sibling;
    hcct_node_t*    parent; // useful?
};

typedef struct hcct_pair_s hcct_pair_t;
struct hcct_pair_s {
    hcct_node_t*    node;
    UINT32          id;
};

hcct_node_t     *root;

hcct_node_t* createTree(FILE* logfile) {    
    char buf[BUF+1];
    char *s;
        
    // Syntax of the first two rows
    // c <tool> [<epsilon> <phi>] [<sampling_interval> <burst_length>]
    // c <command> <process/thread id> <working directory>
    
    // First row
    fgets(buf, BUF, logfile); // contiene anche terminatore di riga!
    s=strtok(buf, " ");
    if (strcmp(s, "c")) {
        printf("Error: wrong format!\n");
        exit(1);
    }
    s=strtok(NULL, " ");
    printf("Log generated by tool: %s", s);
    s=strtok(NULL, " ");
    if (s!=NULL) printf("\nOther parameters:");
    while (s!=NULL) {
        printf(" %s", s);
        s=strtok(NULL, " ");
    }

    // Second row
    fgets(buf, BUF, logfile);
    s=strtok(buf, " ");
    if (strcmp(s, "c")) {
        printf("Error: wrong format!\n");
        exit(1);
    }
    s=strtok(NULL, " ");
    printf("Instrumented program:");
    while (s!=NULL) {
        printf(" %s", s);
        s=strtok(NULL, " ");
    }

    // I need a stack to reconstruct the tree
    hcct_pair_t tree_stack[STACK_MAX_DEPTH];
    int stack_idx=0;
    int nodes=0;
    
    UINT32 node_id, parent_id, counter, routine_id;
    UINT16 call_site;
        
    // Create root node
    hcct_node_t* root=malloc(sizeof(hcct_node_t));    
    fgets(buf, BUF, logfile);
    s=strtok(buf, " ");        
    if (strcmp(s, "v")) {
            printf("Error: wrong format!\n");
            exit(1);
    }
    
    tree_stack[0].node=root;    
    tree_stack[0].id=strtoul(&buf[2], &s, 0); // node_id
    s++; // skip " " character
    if (strtoul(s, &s, 0)!=0) {
            printf("Error: root node cannot have a parent node!\n");
            exit(1);
    }
    s++;
    root->parent=NULL;
    root->first_child=NULL;
    root->next_sibling=NULL;
    root->counter=strtoul(s, &s, 0);    
    s++;
    root->routine_id=strtoul(s, &s, 0);
    s++;
    root->call_site=(unsigned short)strtoul(s, &s, 0);
    if (root->counter!=1 || root->routine_id!=0 || root->call_site!=0) {
            printf("Error: there's something strange in root node data (counter, routine_id or call_site)!\n");
            exit(1);
    }
    nodes++;
        
    // Syntax: v <node id> <parent id> <counter> <routine_id> <call_site>    
    hcct_node_t *node, *parent, *tmp;
    while(1) {
        fgets(buf, BUF, logfile);
        s=strtok(buf, " ");        
        if (strcmp(s, "p")==0) break;
        if (strcmp(s, "v")) {
            printf("Error: wrong format!\n");
            exit(1);
        }
        
        node=malloc(sizeof(hcct_node_t));
        node_id=strtoul(&buf[2], &s, 0);
        s++;    
        parent_id=strtoul(s, &s, 0);
        s++;
        node->counter=strtoul(s, &s, 0);
        s++;
        node->routine_id=strtoul(s, &s, 0);
        s++;
        node->call_site=(unsigned short)strtoul(s, &s, 0);
        
        // Attach node to the tree
        while (tree_stack[stack_idx].id!=parent_id && stack_idx>=0)
            stack_idx--;
        if (tree_stack[stack_idx].id!=parent_id) {
            printf("Error: log file is broken - missing node(s)\n");
            exit(1);            
        }        
        parent=tree_stack[stack_idx].node;
        node->parent=parent;
        node->first_child=NULL;
        node->next_sibling=NULL;
        if (parent->first_child==NULL)
            parent->first_child=node;
        else {
            // Attach as rightmost child
            for (tmp=parent->first_child; tmp->next_sibling!=NULL; tmp=tmp->next_sibling);
            tmp->next_sibling=node;                        
        }
        stack_idx++;
        tree_stack[stack_idx].node=node;
        tree_stack[stack_idx].id=node_id;
        nodes++;
    }
    
    // Sanity check
    if (strtoul(&buf[2], NULL, 0)!=nodes) {
        printf("Error: log file is broken - wrong number of nodes\n");
        exit(1);
    }
    
    printf("Total number of nodes: %lu\n", nodes);
    
    return root;
}


int main(int argc, char* argv[]) {
    if (argc!=2) {
        printf("Syntax: %s <logfile>\n", argv[0]);
        exit(1);
    }
    FILE* logfile;
    logfile=fopen(argv[1], "r");
    // CHECK FOPEN
    root=createTree(logfile);
    return 0;
}
